# geteway 访问地址 http://localhost:10010/user/1
server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes: #路由规则
        - id: user-service # 自定义路由标示，必须唯一
          # url: http;//127.0.0.1：8080 http固定地址
          uri: lb://userservice # 路由的目标地址  lb 就是loadbalance 负载均衡 后面服务名称
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合 有十几个
     #     filters: 给所有进入userservice的请求添加一个请求头：Truth=itcast is freaking awesome!
      #      -  AddRequestHeader=Truth, Itcast is freaking awesome! # 添加请求头 AddRequestHeader=Truth, Itcast is freaking awesome! # 添加请求头
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
          #  - after=2047-01-20T17:42:47.789-07:00[America/Denver]
      default-filters: # （所有请求）过滤器， 经过断言工厂后进行过滤 AddRequestHeader 增加请求头
        - AddRequestHeader=Truth,Itcast is freaking awesome!


  #我们在配置文件中写的断言规则只是字符串，这些字符串会被Predicate Factory读取并处理，转变为路由判断的条件
 # 例如Path=/user/**是按照路径匹配，这个规则是由org.springframework.cloud.gateway.handler.predicate.PathRoutePredicateFactory类来处理的
  #像这样的断言工厂在SpringCloudGateway还有十几个
